import { useState } from 'react';
import Layout from '@/components/Layout';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Copy, Code, ExternalLink, Zap, Target, TrendingUp, CheckCircle } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { useQuery } from '@tanstack/react-query';
import RedtrackConfigManager from '@/components/RedtrackConfigManager';

export default function RedTrackPage() {
  const [redtrackDomain, setRedtrackDomain] = useState('');
  const [generatedTag, setGeneratedTag] = useState('');
  const { toast } = useToast();

  // Get user info for generating tracking tags
  const { data: user } = useQuery({
    queryKey: ['/api/auth/user'],
  });

  const generateTrackingTag = () => {
    if (!redtrackDomain.trim()) {
      toast({
        title: 'Error',
        description: 'Please enter your RedTrack domain',
        variant: 'destructive',
      });
      return;
    }

    const userId = (user as any)?.id || 'USER_ID';
    const trackingCode = `<!-- RedTrack Tracking Tag - Generated by CallCenter Pro -->
<script>
  (function() {
    // RedTrack Integration Script
    window.redtrackConfig = {
      domain: '${redtrackDomain}',
      userId: ${userId},
      endpoint: window.location.origin + '/api/tracking/redtrack'
    };
    
    // Capture URL parameters
    const urlParams = new URLSearchParams(window.location.search);
    const trackingData = {
      clickid: urlParams.get('clickid'),
      campaign_id: urlParams.get('campaign_id') || urlParams.get('cid'),
      offer_id: urlParams.get('offer_id') || urlParams.get('oid'),
      source: urlParams.get('source') || urlParams.get('utm_source'),
      medium: urlParams.get('medium') || urlParams.get('utm_medium'),
      campaign: urlParams.get('campaign') || urlParams.get('utm_campaign'),
      timestamp: new Date().toISOString(),
      url: window.location.href,
      referrer: document.referrer || 'direct',
      userAgent: navigator.userAgent
    };
    
    // Store in session for later use
    if (trackingData.clickid) {
      sessionStorage.setItem('redtrack_data', JSON.stringify(trackingData));
      console.log('RedTrack data captured:', trackingData);
    }
    
    // Send initial tracking event
    fetch(window.redtrackConfig.endpoint + '/session', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(trackingData)
    }).catch(e => console.log('RedTrack tracking error:', e));
    
    // Track phone clicks for conversion
    document.addEventListener('click', function(e) {
      const target = e.target.closest('a[href^="tel:"]');
      if (target && trackingData.clickid) {
        fetch(window.redtrackConfig.endpoint + '/conversion', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            ...trackingData,
            eventType: 'phone_click',
            phoneNumber: target.href.replace('tel:', ''),
            conversionValue: 25.00 // Default value
          })
        }).catch(e => console.log('RedTrack conversion error:', e));
        
        // Send postback to RedTrack
        if (window.redtrackConfig.domain) {
          const postbackUrl = \`https://\${window.redtrackConfig.domain}/postback?clickid=\${trackingData.clickid}&sum=25&type=ConvertedCall\`;
          fetch(postbackUrl, { method: 'GET', mode: 'no-cors' }).catch(() => {});
        }
      }
    });
  })();
</script>`;

    setGeneratedTag(trackingCode);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedTag);
    toast({
      title: 'Copied!',
      description: 'Tracking tag copied to clipboard',
    });
  };

  return (
    <Layout>
      <div className="space-y-6">
        {/* Header Section */}
        <div className="space-y-2">
          <h1 className="text-3xl font-bold">RedTrack Tracking Tags</h1>
          <p className="text-muted-foreground">
            Generate universal tracking tags for RedTrack attribution - add to any landing page
          </p>
        </div>

        {/* Features Overview */}
        <div className="grid md:grid-cols-3 gap-4">
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center gap-2 text-lg">
                <Target className="h-5 w-5 text-blue-500" />
                Universal Tracking
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                One tracking tag works on all landing pages - automatically captures RedTrack parameters
              </p>
            </CardContent>
          </Card>
          
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center gap-2 text-lg">
                <Zap className="h-5 w-5 text-green-500" />
                Auto Postbacks
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Automatically sends conversion data to RedTrack when visitors call your numbers
              </p>
            </CardContent>
          </Card>
          
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center gap-2 text-lg">
                <TrendingUp className="h-5 w-5 text-purple-500" />
                Easy Setup
              </CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">
                Enable RedTrack's AI-powered campaign optimization with conversion data
              </p>
            </CardContent>
          </Card>
        </div>

        {/* Integration Information */}
        <Card className="bg-blue-50 dark:bg-blue-950/20 border-blue-200 dark:border-blue-800">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <ExternalLink className="h-5 w-5" />
              How RedTrack Integration Works
            </CardTitle>
            <CardDescription>
              Complete attribution flow from click to conversion
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid md:grid-cols-2 gap-6">
              <div>
                <h4 className="font-semibold mb-2">1. Click Tracking</h4>
                <p className="text-sm text-muted-foreground">
                  RedTrack sends visitors to your landing pages with clickid parameters. Our system automatically captures and stores these for attribution.
                </p>
              </div>
              <div>
                <h4 className="font-semibold mb-2">2. Session Management</h4>
                <p className="text-sm text-muted-foreground">
                  Visitor sessions are tracked with RedTrack campaign data, including offer IDs and campaign information for precise tracking.
                </p>
              </div>
              <div>
                <h4 className="font-semibold mb-2">3. Conversion Events</h4>
                <p className="text-sm text-muted-foreground">
                  When calls are made or forms submitted, conversion events are created with revenue data and attribution details.
                </p>
              </div>
              <div>
                <h4 className="font-semibold mb-2">4. Postback Delivery</h4>
                <p className="text-sm text-muted-foreground">
                  Conversion data is automatically sent to RedTrack via postback URLs for optimization and performance tracking.
                </p>
              </div>
            </div>
            
            <div className="pt-4 border-t">
              <h4 className="font-semibold mb-2">Sample Postback URL Format</h4>
              <div className="bg-white dark:bg-gray-900 p-3 rounded font-mono text-sm border">
                https://your.redtrack.domain/postback?clickid={'{'}clickid{'}'}&sum=20&type=ConvertedCall
              </div>
              <p className="text-xs text-muted-foreground mt-1">
                Postbacks include clickid for attribution, revenue amount, and conversion type
              </p>
            </div>
          </CardContent>
        </Card>

        {/* Configuration Manager */}
        <RedtrackConfigManager />
      </div>
    </Layout>
  );
}